# https://github.com/linuxsoftware/ls.joyous

dist: xenial

language: python

env:
 - WAGTAIL_VERSION=2.3
 - WAGTAIL_VERSION=2.4
 - WAGTAIL_VERSION=2.5

python:
  - "3.5"
  - "3.6"
  - "3.7"

# matrix:
#   include:
#     - python: 3.7
#       dist: xenial
#       sudo: required
#       env: WAGTAIL_VERSION=2.3
#     - python: 3.7
#       dist: xenial
#       sudo: required
#       env: WAGTAIL_VERSION=2.4

install:
  - pip install -r requirements.txt
  - pip install wagtail==$WAGTAIL_VERSION

script:
  - ./runtests.py --coverage

after_success:
  - coveralls
